{% set name = "pyvo" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3630ad7c62acf9ce435a9b2d997376fa9fae6865ada6632735680c90ccf525e6

build:
  noarch: python
  number: 0
  script: python setup.py install --offline --no-git --single-version-externally-managed --record=files.txt

requirements:
  host:
    - python >=3.5
    - setuptools
    - astropy
    - numpy >=1.14
  run:
    - python >=3.5
    - astropy
    - requests
    - python-mimeparse
    - numpy >=1.14

test:
  imports:
    - pyvo
    - pyvo.dal
    - pyvo.registry
    - pyvo.io
    - pyvo.utils

about:
  home: http://pyvo.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Astropy affiliated package for accessing Virtual Observatory data and services
  description: |
    The goal of `pyvo` is allow astronomers and tool developers to access data
    and services from remote archives and other web resources.  It takes
    advantage VO standards to give access to thousands of catalogs, data
    archives, information services, and analysis tools.  It also takes
    advantage of the general capabilities of Astopy (and numpy), and so a
    secondary goal is to provide a development platform for migrating more VO
    capabilities into Astropy.
  doc_url: http://pyvo.readthedocs.io/
  dev_url: https://github.com/astropy/pyvo

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - funbaker
    - RayPlante
    - cbanek
    - andamian
    - jcsegovia
