{% set name = "pyvo" %}
{% set version = "1.6.2" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea9e80f2a30c39be5564bf46545f7db0af7c6ef5fd1da2836eb435a5007f7802

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools_scm
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base >=4.1
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyvo
    - pyvo.dal
    - pyvo.registry
    - pyvo.io
    - pyvo.utils

about:
  home: http://pyvo.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Astropy affiliated package for accessing Virtual Observatory data and services
  description: |
    The goal of `pyvo` is allow astronomers and tool developers to access data
    and services from remote archives and other web resources.  It takes
    advantage VO standards to give access to thousands of catalogs, data
    archives, information services, and analysis tools.  It also takes
    advantage of the general capabilities of Astopy (and numpy), and so a
    secondary goal is to provide a development platform for migrating more VO
    capabilities into Astropy.
  doc_url: http://pyvo.readthedocs.io/
  dev_url: https://github.com/astropy/pyvo

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - funbaker
    - RayPlante
    - cbanek
    - andamian
    - jcsegovia
