{% set name = "pyvo" %}
{% set version = "0.9.2" %}
{% set hash_type = "sha256" %}
{% set hash_value = "664cfffc1915c08513f9409a53595d00c8fa3c19ba867b5a998b30f281b564f3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - astropy
  run:
    - python
    - astropy
    - requests
    - python-mimeparse

test:
  imports:
    - pyvo
    - pyvo.dal
    - pyvo.registry
    - pyvo.io
    - pyvo.utils

about:
  home: http://pyvo.readthedocs.io/
  license: BSD 3-clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Astropy affiliated package for accessing Virtual Observatory data and services
  description: |
    The goal of `pyvo` is allow astronomers and tool developers to access data
    and services from remote archives and other web resources.  It takes
    advantage VO standards to give access to thousands of catalogs, data
    archives, information services, and analysis tools.  It also takes
    advantage of the general capabilities of Astopy (and numpy), and so a
    secondary goal is to provide a development platform for migrating more VO
    capabilities into Astropy.
  doc_url: http://pyvo.readthedocs.io/
  dev_url: https://github.com/pyvirtobs/pyvo

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - funbaker
    - RayPlante
