travis:
  secure:
    BINSTAR_TOKEN: GhltwfD8/55A05WpmzQb8DcbB2p1+jL3d4jqo5KI+CbA89Sri2voGyeVHV8SMYWCw3rhN4p3MX/KVpCrKP3GcIcbF0eD5WSA94lMbi9gSASeuzbQ6TJGpSwIfuNcF+YgSYWmvgAjExBZ+rk9TgdFxaw8YuejXNHxISEb6vwlnsMJ2XHgyJ095yHHZDQec7mfl0oI2BxGbeHNjJQiga+4ZZu0eQSi98U2kqAyHC99XDBp0WDg6TCcmx4swK0fuuludXxNL3hmUHZ3ePjFAKnhzc8Pi4Z99JsD91gJh+SNvEP7hmFSYMu/lCFs6sFCA41PCQ5SkTA8lTYEv3xmxpeyo9S4wrDDi3uU1fZsSkLnzZfIrsmXgSE16tYEr5aOK30wEA2qR43WZEQXb/JVfL35y/M+RMSZIopXLrXd9Gk8Zbh1EnZWCF4/ccYdRhokXGDln4A8NcHojFNEhOfgJ5hQSH4k/X32dgQKJtW2gAIG7Z6Xy1lr47DSdx/CJJ14395mK+O2Xjytt/oWYslZpHsdFQVUG+IsHB9x/Ib3e3L/ztjfPdQh6ldjdlvNRhErPM2aHT7dE6BUak3JbnyEPG+EcqilPZO+z+ljZQoiAx5PbMW2vvFU939RJsUmoQO7aU/JZGvTXcRoCbig3MND/WDVa3c/3r/ueinFT8YnKdJw+Ho=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
